# Site settings
title: 前端养成记
email: loyalsoldier@qq.com
description: > # this means to ignore newlines until "baseurl:"
  关于网页重构、前端开发、设计等。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  loyalsoldier

# Build settings
markdown: kramdown
